<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '17',
    'typeid' => '0',
    'title' => '9月份幸28红包争霸赛开赛',
    'style' => ';bold',
    'thumb' => '',
    'keywords' => '竞猜',
    'description' => '  ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=17&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1500961829',
    'updatetime' => '1505825935',
    'hitsid' => 'c-1-3',
    'views' => '90',
    'yesterdayviews' => '18',
    'dayviews' => '12',
    'weekviews' => '30',
    'monthviews' => '54',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '17',
    'typeid' => '0',
    'title' => '会员推广福利',
    'style' => ';bold',
    'thumb' => '/uploadfile/2017/0913/20170913111256481.jpg',
    'keywords' => '公告',
    'description' => '会员推广有奖',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=17&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1505269608',
    'updatetime' => '1505789063',
    'hitsid' => 'c-1-8',
    'views' => '25',
    'yesterdayviews' => '10',
    'dayviews' => '7',
    'weekviews' => '7',
    'monthviews' => '25',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '17',
    'typeid' => '0',
    'title' => '赢金豆抢红包兑大奖',
    'style' => ';bold',
    'thumb' => '/uploadfile/2017/0917/20170917110150265.jpg',
    'keywords' => '兑奖',
    'description' => '赢金豆兑大奖',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=17&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1505616435',
    'updatetime' => '1505796442',
    'hitsid' => 'c-1-10',
    'views' => '22',
    'yesterdayviews' => '1',
    'dayviews' => '9',
    'weekviews' => '10',
    'monthviews' => '22',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '17',
    'typeid' => '0',
    'title' => '幸运28的投注技巧',
    'style' => ';bold',
    'thumb' => '',
    'keywords' => '竞猜',
    'description' => '常用的幸运28投注方法',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=17&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1501923193',
    'updatetime' => '1505788315',
    'hitsid' => 'c-1-4',
    'views' => '29',
    'yesterdayviews' => '1',
    'dayviews' => '4',
    'weekviews' => '5',
    'monthviews' => '10',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '17',
    'typeid' => '0',
    'title' => '会员福利来袭--全国手机充值费用比淘宝网还低',
    'style' => ';bold',
    'thumb' => '',
    'keywords' => '活动',
    'description' => '全国各地手机充值费用低、到帐快、返利多',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=17&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1505269608',
    'updatetime' => '1505788332',
    'hitsid' => 'c-1-7',
    'views' => '10',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '10',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '17',
    'typeid' => '0',
    'title' => '会员每日登录福利',
    'style' => ';bold',
    'thumb' => '',
    'keywords' => '公告',
    'description' => '每日登录有奖',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=17&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1505268159',
    'updatetime' => '1505789053',
    'hitsid' => 'c-1-6',
    'views' => '8',
    'yesterdayviews' => '1',
    'dayviews' => '3',
    'weekviews' => '4',
    'monthviews' => '8',
  ),
);
?>